# Generated by Django 4.1.5 on 2024-11-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwicConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_base_url', models.CharField(default='https://theweekinchess.com/zips/', max_length=255)),
                ('download_number_pattern', models.CharField(default='twic<<number>>g.zip', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwicFolderConfigModel',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('download_folder_path', models.CharField(max_length=255)),
                ('unzip_folder_path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwicStatusModel',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lichessfolderconfigmodel',
            name='unzip_folder_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
