# Generated by Django 4.1.5 on 2024-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_twicconfigmodel_twicfolderconfigmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichessfolderconfigmodel',
            name='reduced_folder_path',
        ),
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='elo_min_commented',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='elo_min_eco',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='lichessconfigmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lichessfolderconfigmodel',
            name='unzip_folder_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lichessstatusmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twicconfigmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
