# Generated by Django 4.1.5 on 2024-12-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_remove_lichessfolderconfigmodel_reduced_folder_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichessfolderconfigmodel',
            name='script_folder_path',
        ),
        migrations.AlterField(
            model_name='lichessconfigmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lichessstatusmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twicconfigmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
