# Generated by Django 4.1.5 on 2024-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_lichessfolderconfigmodel_eco_complete_folder_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichessconfigmodel',
            name='script_name_unzst',
            field=models.CharField(default='concat_pgn.sh', max_length=255),
        ),
    ]
